language: elixir
sudo: false
elixir:
  - 1.4
  - 1.5
otp_release:
  - 19.3
  - 20.0
script: mix test.ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
services:
  - redis-server
  - memcached
notifications:
  recipients:
    - moski.doski@gmail.com
